Made calculating amount easier
Seggan/SFCalc pull request #16
Opened 2021-03-24 15:35 UTC by RobotHanzo

This offers the ability to calculate in stacks instead of raw numbers, which is more convenient when counting the materials, as Minecraft measures in stacks of 64

**The only bad sides for the user currently is they would have to somehow regenerate their config, due to new keys and changed configs**

Demonstration:
![Screenshot](https://cdn.robothanzo.dev/javaw_JDzpTHRdwi.png)

2021-03-24 15:39 UTC, Seggan commented
Thank you for creating this pull request! Unfortunately I need to include a part of the code that regenerated the config, so you'll have to wait for it.

2021-03-24 15:40 UTC, Seggan requested changes

2021-03-24 15:40 UTC, Seggan commented on src/main/java/io/github/seggan/sfcalc/Calculator.java
> +                }
stack amounts arent always 64

2021-03-24 15:46 UTC, RobotHanzo commented on src/main/java/io/github/seggan/sfcalc/Calculator.java
> +                }
I will fix that tomorrow

2021-03-25 15:10 UTC, RobotHanzo commented on src/main/java/io/github/seggan/sfcalc/Calculator.java
> +                }
Fixed.

2021-03-25 15:37 UTC, Seggan requested changes
have you tested these changes?

2021-03-25 15:37 UTC, Seggan commented on src/main/java/io/github/seggan/sfcalc/Calculator.java
> +import java.util.*;
No star imports please

2021-03-25 15:37 UTC, Seggan commented on src/main/java/io/github/seggan/sfcalc/Calculator.java
> +                if (originalValues <= entry.getKey().getMaxStackSize()) {
```suggestion
				int stackSize = entry.getKey().getMaxStackSize();
                if (originalValues <= stackSize) {
```
cache stack size

2021-03-25 15:37 UTC, Seggan commented on src/main/java/io/github/seggan/sfcalc/Calculator.java
> +                        plugin.neededString, parsedAmount, WordUtils.capitalizeFully(ChatColor.stripColor(ItemUtils.getItemName(entry.getKey())))));
dont really need wordutils now

2021-03-25 15:37 UTC, Seggan commented on src/main/java/io/github/seggan/sfcalc/Calculator.java
> +                if (originalValues <= entry.getKey().getMaxStackSize()) {
same here. cache stack sizes

2021-03-25 15:37 UTC, Seggan commented on src/main/java/io/github/seggan/sfcalc/Calculator.java
> +                        plugin.amountString, parsedAmount, WordUtils.capitalizeFully(ChatColor.stripColor(ItemUtils.getItemName(entry.getKey())))));
and here with wordutils

2021-03-25 15:37 UTC, Seggan commented on src/main/java/io/github/seggan/sfcalc/Calculator.java
> +                    add(recipe, new ItemStack(Material.DIAMOND, 9), 9);
youre adding 9 diamonds 9 times... thats 81 diamonds for 1 metal forge use

2021-03-25 15:42 UTC, RobotHanzo commented
> have you tested these changes?

Did test them, but didnt test the metal forge
And some weird looking stuff like star imports was caused by intelij refractor :P

2021-03-25 16:09 UTC, Seggan commented
Btw theres a setting where you can disable intellij star imports. Look it up on Google

2021-03-26 11:05 UTC, RobotHanzo commented
Changes tested, plugin still works

2021-03-26 11:48 UTC, Seggan approved these changes
I will need to skip the build as I need to rewrite certain parts of SFCalc

2021-03-26 11:50 UTC, merged